### ISSUE TITLE
About the dataset download

### ISSUE THREAD

**Issue by wgqtmac** [dcharatan/pixelsplat#114]
Hi, Thanks for your excellent work!

The preprocessed version of RealEstate10K link is broken (http://schadenfreude.csail.mit.edu:8000/). Can you provide a new link?

Best regards

**Comment by dcharatan** [comment]
Should be fixed now; sorry about that!

**Comment by Yang-xiao-uts** [comment]
> Should be fixed now; sorry about that!
Hi, the link http://schadenfreude.csail.mit.edu:8000/ is broken again. Could you please help restore it? Thank you!

**Comment by wgqtmac** [comment]
I'm sorry for not getting back to you sooner. This link  http://schadenfreude.csail.mit.edu:8000/ can not work well right now. 
I wonder if it’s because of the Chinese IP?

**Comment by Yang-xiao-uts** [comment]
Maybe, both I (from Australia) and a colleague in China receive connection‑error or “has been denied” messages. Could you please confirm whether the server is temporarily down and, if possible, provide an alternative download link or mirror for the files?
Many thanks for your help!

**Comment by Gynjn** [comment]
@dcharatan Could you check the link? Thanks in advance!

**Comment by ktertikas** [comment]
Hello, I am getting an "Unable to connect" error message in the browser when trying to access the above url (trying from Greece). It would be great if you could have a look at this @dcharatan !

**Comment by dcharatan** [comment]
Should be fixed now. We're looking into a different way to host the dataset as well.

**Comment by Tungthanhlee** [comment]
Hello, have you fixed the link yet? I still can't get access to the download link.

**Comment by longxiang-ai** [comment]
@dcharatan Could you please check the link? I can't get access to the download link now.

**Comment by Dong-Huo** [comment]
Could you please check the line http://schadenfreude.csail.mit.edu:8000/? It shows "refused to connect". Thank you.
